first_name: Mami
last_name: Ravaloarison

location: New York, USA
email: mravaloarison@gmail.com

cv_pdf: /assets/pdf/resume.pdf

github: mravaloarison
linkedin: mravaloarison

url: https://mravaloarison.github.io
baseurl:

about_me: |
    My name is Mami, and I’m a Software Engineer from Madagascar. I came to the United States in 2021 to study Computer Information Systems at <a href="https://www.monroe.edu/">Monroe University</a> and graduated in June 2025 with a Bachelor of Science and a minor in Mathematics. 

    Currently, I work as a Junior Data Analyst in New York City, which I know sounds different from the title I use, but my tasks are very broad, and I also learn a lot from them. At work, I recreate legacy dashboards in Power BI, build and maintain SharePoint sites for my department and was recently assigned to redesign my old University’s library website using <a href="https://www.springshare.com/libguides/">SpringShare’s LibGuides</a> platform as a side project. 

    I chose Software Engineer because building software makes me feel like I am a magician doing a bunch of tricks behind the scenes, and then my users go “wow.” I think it is fun and I also believe that right now is a very exciting time to be a developer because of AI. It reduces a lot of development time and makes it easy to build things much faster. 

    When I was a student, my work authorization was limited to on-campus jobs because of my F1 visa status, so I started going to hackathons instead to get more exposure building software, working with different teams and under deadlines, experimenting with many APIs, SDKs, and new frameworks. 

    At one point I was honestly obsessed with hackathons, because during my academic years I won 12 of them across different U.S. Eastern universities like <a href="https://www.yale.edu/">Yale</a>, <a href="https://www.princeton.edu/">Princeton</a>, <a href="https://www.stonybrook.edu/">Stony Brook</a>, and more. 

    Outside of tech, I used to hate reading and writing, but I recently started pushing myself to do both more often. I also try to consistently cook healthy meals and go to the gym, though I’m still working on making those habits stick. Other things I love:
    - Dogs
    - Piano, guitar, and bass
    - Chess
    - Video games

sections:
    Education:
        - institution: Monroe University
          location: Bronx, New York
          url: https://www.monroeu.edu/
          area: Computer Information Systems
          studyType: Bachelor of Science (Magna Cum Laude)
          start_date: 2021
          end_date: 2025
          score: "3.7/4.0 GPA"
          minor: Mathematics

        - institution: Lycée Privé ACEEM
          location: Madagascar
          url: https://www.youtube.com/@aceemgroupe8437
          area: Scientific
          studyType: Baccalauréat
          start_date: 2015
          end_date: 2018

    Experience:
        - company: Office of Academic Records, Assessment, and Planning, Monroe University
          position: Junior Data Analyst
          location: New Rochelle, New York
          start_date: 2025
          end_date: ongoing
          highlights:
              - Recreating and Optimizing 100+ dashboards on PowerBI to help the university track student performance, retention, and graduation rates.
              - Built a SharePoint site for the ARAP department to streamline data sharing and collaboration among team members.
              - Updated the University's Library website using HTML, CSS, JavaScript and LibGuide platform to enhance user experience and accessibility.

        - company: Student Success Center, Monroe University
          position: Information Technology Peer Tutor
          location: Bronx, New York
          start_date: 2023
          end_date: 2025
          highlights:
              - Tutored students in Excel, databases, and Programming across multiple academic levels.
              - Assisted alumni with real-world IT issues, including e-commerce website setup and troubleshooting.

        - company: New Rochelle Council of Community Services
          position: Software Developer Intern
          location: New Rochelle, New York
          start_date: 2023
          end_date: 2023
          highlights:
              - Collaborated with a team to redesign the nonprofit's website using Next.js (TypeScript) and Tailwind CSS.
              - Implemented Figma wireframes into functional interfaces and recreated designs using WordPress theme and plugins.

        - company: Residence Life, Monroe University
          position: Resident Assistant
          location: New Rochelle, New York
          start_date: 2022
          end_date: 2023
          highlights:
              - Supported 50+ dorm rooms by resolving conflicts, reporting maintenance issues, and providing resources to students.
              - Planned and led 10+ events per semester while collaborating with fellow RAs and Residence life staff to promote community engagement.

    Awards:
        - title: 12 Hackathon wins
          date: 2022-2024
          awarder: Several East Coast Universities & Major League Hacking
          url: https://devpost.com/mrava
          summary: 12 Hackathon wins across the U.S. (Yale, Princeton, Stony Brook, RPI, University of Penn), earning ~$4,000 in prizes.

        - title: Dean's Award for Academic Excellence
          date: 2025
          awarder: Monroe University
          summary: Awarded for outstanding academic achievement, leadership and impact.

    Languages:
        - name: Malagasy
          summary: "Native speaker"

        - name: English
          summary: "Fluent"

        - name: French
          summary: "Fluent (DELF B2 Certified)"

    Interests:
        - name: Applied AI & Data Systems
          icon: bi-tag
          keywords: "Machine Learning, Deep Learning, Data Analysis, Data Visualization, Big Data, Data Engineering, MCP, RAG"

    Certificates:
        - name: CS50P - Introduction to Programming with Python
          date: 2022
          issuer: Harvard University
          icon: bi-tag

        - name: DELF B2 - French Language Proficiency
          date: 2020
          issuer: Alliance Française Madagascar
          icon: bi-tag

# BLOG CONFIGURATION
blog_description: >
    This is just a space where I write about whatever I’m thinking through, my honest thoughts on different subjects.

# PROJECTS CONFIGURATION
projects_description: >
    This page is a collection of few projects i have built over time. Each one taught me something new about technology, design, or how to think better.

collections:
    projects:
        output: true
        permalink: /projects/:name/
